### ISSUE TITLE
reformat.rb alphabetizes oddly

### ISSUE THREAD

**Issue by benlachman** [orbitalindex/awesome-space#14]
Alphabetical sort doesn't seem to do the right thing in a few edge cases.

See https://github.com/orbitalindex/awesome-space/commit/5e16b6cd13b5a2982e927c52807d8d7ba51a447b#diff-04c6e90faac2675aa89e2176d2eec7d8R134

**Comment by cantino** [comment]
Maybe we need to sort irrespective of capital letters?

**Comment by benlachman** [comment]
Yeah, a case insensitive sort is probably the right thing.

**Comment by cantino** [comment]
Fixed in 3aa5ca704bec5efec8bff6be421e63e60322030f
