### ISSUE TITLE
Software section titles are confusing

### ISSUE THREAD

**Issue by skypanther** [orbitalindex/awesome-space#23]
By Astronomy Software, I thought you mean "general purpose astronomy software" and by Interactive Planetariums you meant specifically sky simulator programs. After I made my initial commit on #22 I realized that all the Astronomy Software items there are mostly tools for software developers -- like AstroPy. Or, at least I think that's what you mean by that category.

Maybe the categories should be _SDK and Software Development Tools_ and _Astronomy Software_?

**Comment by cantino** [comment]
That's a great suggestion @skypanther, would you like to make the change?

**Comment by skypanther** [comment]
#24 <-- There you go!

**Comment by cantino** [comment]
Thanks, merged!
