### ISSUE TITLE
Pull in open source projects from the hackaday.io list (comments)

### ISSUE THREAD

**Issue by patrickwalton** [orbitalindex/awesome-space#32]
This hackaday.io list has some open source components not on your list: https://hackaday.io/list/4321-satellite-projects

**Comment by benlachman** [comment]
Happy to include. Think we should include all of them, or just a selection? 

Will review a PR if you create one!

**Comment by patrickwalton** [comment]
I think all open source spacecraft stuff is awesome, so I say include it
all (or just a link to their list).

**Comment by cantino** [comment]
Done in 19a3c2d. Thanks @patrickwalton.
