### ISSUE TITLE
Orb viewer and orbcalc

### ISSUE THREAD

**Issue by wselwood** [orbitalindex/awesome-space#5]
I'm raising this as an issue rather than a pr because I'm tooting my own horn here and I'm not sure how you feel about that.

A visualisation of all the asteroids we know about in the solar system: http://parsecsreach.com/orbviewer/

A library of fast go code used to create the data behind orbviewer: https://github.com/wselwood/orbcalc

**Comment by cantino** [comment]
Hey @wselwood! These seem quite cool (nice work!), go ahead and submit a PR adding them and I'll merge it.
