### ISSUE TITLE
Is this for open source tools only?

### ISSUE THREAD

**Issue by supersonic71** [orbitalindex/awesome-space#57]
If not, can I add Space Engine under visualizations? 
SpaceEngine - https://www.youtube.com/watch?v=nq8YsgGghDc

**Comment by cantino** [comment]
It's generally for open source, but I'd be okay with SpaceEngine being included. It's a pretty special project.

**Comment by supersonic71** [comment]
Closing as https://github.com/orbitalindex/awesome-space/pull/58 was accepted.
