### ISSUE TITLE
Launch Library 1 and Space Launch Now API replaced by Launch Library 2

### ISSUE THREAD

**Issue by Nosudrum** [orbitalindex/awesome-space#60]
Hello,

Just a heads up for your Launches section, the Launch Library 1 and Space Launch Now APIs have both been replaced by the [Launch Library 2 API](https://thespacedevs.com/llapi) maintained by [The Space Devs](https://thespacedevs.com/) in July 2020.

You can find the official announcements at the following links : 
- On the now deprecated [Launch Library Discord server](https://discord.gg/6pHrA6uXM5) : [announcement link](https://discordapp.com/channels/307940455138721793/735476071469809752/735476700959342674)
- On the [Space Launch Now Discord server](https://discord.gg/RUWdVVx) : [announcement link](https://discordapp.com/channels/380226438584074242/380226845574037505/735483025114005555)

Might be worth linking the [TSD Discord server](https://discord.gg/wxEGcWXbsD) as well, where news and support about the LL2 API (as well as other APIs) are provided.

Additionally, you might be interested in linking the following APIs : 
- [Spaceflight News API](https://spaceflightnewsapi.net/), provided by The Space Devs as well
- [Launch Dashboard API](https://github.com/shahar603/Launch-Dashboard-API), a TSD Partner API (currently out-of-date but might still be interesting)

Feel free to @ me if you have any question

**Comment by cantino** [comment]
Thanks! Would you mind sending us a PR?

**Comment by Nosudrum** [comment]
https://github.com/orbitalindex/awesome-space/pull/61
